#!/bin/bash
## ~/.config/lf/previewer_sandbox

exec 3> /dev/tty

set -euo pipefail
(
    exec bwrap \
     --ro-bind /usr/bin /usr/bin \
     --ro-bind /usr/share/ /usr/share/ \
     --ro-bind /usr/lib /usr/lib \
     --ro-bind /usr/lib64 /usr/lib64 \
     --symlink /usr/bin /bin \
     --symlink /usr/bin /sbin \
     --symlink /usr/lib /lib \
     --symlink /usr/lib64 /lib64 \
     --proc /proc \
     --dev /dev \
     --ro-bind /etc /etc \
     --ro-bind /mnt /mnt \
     --ro-bind ~/.config ~/.config \
     --ro-bind ~/.cache ~/.cache \
     --bind ~/.cache/vidthumb ~/.cache/vidthumb \
     --ro-bind ~/dotfiles ~/dotfiles \
     --ro-bind "$PWD" "$PWD" \
     --unshare-all \
     --new-session \
     /usr/bin/bash ~/.config/lf/previewer "$@"
)
