gui:
  showIcons: true
  nerdFontsVersion: "3"

git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
  overrideGpg: true

os:
  editPreset: "nvim"

keybinding:
  universal:
    quit: "q"
    quit-alt1: "<c-c>"
