#!/bin/sh
draw() {
	kitten icat --stdin no --transfer-mode stream --place "${w}x${h}@${x}x${y}" "$1" </dev/null >&3
	perl -MPOSIX -e 'POSIX::tcdrain(3)'
	exit 1
}

file="$1"
w="$2"
h="$3"
x="$4"
y="$5"

case "$(file -Lb --mime-type "$file")" in 
  image/*)
    draw "$file"
    ;;
  video/*)
    # vidthumb is from here:
    # https://raw.githubusercontent.com/duganchen/kitty-pistol-previewer/main/vidthumb
    draw "$(~/.config/lf/vidthumb "$file")"
    ;;
esac

bat --color=always --style=plain --line-range=:$h --terminal-width=$w "$file" 2>/dev/null || file -b "$file"
