#!/usr/bin/env bash
set -euo pipefail
exec 3>/dev/tty

real_file="$(realpath -- "$1")"
file_dir="$(dirname -- "$real_file")"
shift

bwrap_args=(
    --ro-bind /usr /usr
    --symlink /usr/bin /bin
    --symlink /usr/bin /sbin
    --symlink /usr/lib /lib
    --proc /proc
    --dev /dev
    --ro-bind /etc /etc

    --tmpfs /tmp

    --ro-bind "$file_dir" "$file_dir"
    --ro-bind "$HOME/.config/lf" "$HOME/.config/lf"

    --ro-bind "$HOME/.cache" "$HOME/.cache"
    --bind "$HOME/.cache/vidthumb" "$HOME/.cache/vidthumb"

    --unshare-all
    --new-session
    --die-with-parent
)

[[ -d /usr/lib64 ]] && bwrap_args+=(--symlink /usr/lib64 /lib64)

[[ -d "$HOME/.local/state/mpv/watch_later" ]] && bwrap_args+=(
    --ro-bind "$HOME/.local/state/mpv/watch_later" \
              "$HOME/.local/state/mpv/watch_later"
)

exec bwrap "${bwrap_args[@]}" \
    /usr/bin/bash "$HOME/.config/lf/previewer" "$real_file" "$@"
